[package]
name = "parsers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
lopdf = "0.39"
natord.workspace = true
pdfium-render.workspace = true
regex = "1"
unrar.workspace = true
zip = { version = "8", default-features = false, features = ["deflate"] }
flate2 = "1"
tracing.workspace = true
