name: Deploy with Docker Compose

on:
  push:
    branches:
      - main # adapte la branche que tu veux déployer

jobs:
  deploy:
    runs-on: mac-orbstack-runner # le nom que tu as donné au runner
    steps:
      - name: Deploy stack
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          BUILDKIT_PROGRESS=plain cd /Users/julienfroidefond/Sites/docker-stack && docker pull julienfroidefond32/stripstream-backoffice && docker pull julienfroidefond32/stripstream-api && docker pull julienfroidefond32/stripstream-indexer && ./scripts/stack.sh up stripstream
