use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::OpenApi;

// ─── Client API (read scope) ────────────────────────────────────────────────

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::books::list_books,
        crate::books::get_book,
        crate::books::get_thumbnail,
        crate::books::pages::get_page,
        crate::series::list_series,
        crate::series::list_all_series,
        crate::series::get_series_by_id,
        crate::series::get_series_by_name,
        crate::series::get_series_metadata_by_id,
        crate::series::ongoing_series,
        crate::series::ongoing_books,
        crate::series::series_statuses,
        crate::series::provider_statuses,
        crate::series::get_related_series,
        crate::series::get_recommendations,
        crate::series::list_favorites,
        crate::series::is_favorite,
        crate::reading::progress::get_reading_progress,
        crate::reading::progress::update_reading_progress,
        crate::reading::progress::mark_series_read,
        crate::search::search_books,
        crate::authors::list_authors,
        crate::stats::get_stats,
        crate::libraries::list_libraries,
        crate::metadata::handlers::get_metadata_links,
        crate::metadata::handlers::get_missing_books,
        crate::reading_lists::list_reading_lists,
        crate::reading_lists::get_reading_list,
    ),
    components(
        schemas(
            crate::reading_lists::ReadingListDto,
            crate::reading_lists::ReadingListDetailDto,
            crate::reading_lists::ReadingListSeriesDto,
            crate::books::ListBooksQuery,
            crate::books::BookItem,
            crate::books::BooksPage,
            crate::books::BookDetails,
            crate::books::pages::PageQuery,
            crate::series::SeriesItem,
            crate::series::SeriesPage,
            crate::series::ListAllSeriesQuery,
            crate::series::OngoingQuery,
            crate::series::SeriesMetadata,
            crate::series::SeriesLookup,
            crate::series::RelatedSeriesItem,
            crate::series::RecommendedSeriesItem,
            crate::series::RecommendationsQuery,
            crate::series::RelatedSeriesQuery,
            crate::reading::progress::ReadingProgressResponse,
            crate::reading::progress::UpdateReadingProgressRequest,
            crate::reading::progress::MarkSeriesReadRequest,
            crate::reading::progress::MarkSeriesReadResponse,
            crate::search::SearchQuery,
            crate::search::SearchResponse,
            crate::search::SeriesHit,
            crate::authors::ListAuthorsQuery,
            crate::authors::AuthorItem,
            crate::authors::AuthorsPageResponse,
            crate::stats::StatsResponse,
            crate::stats::StatsOverview,
            crate::stats::ReadingStatusStats,
            crate::stats::FormatCount,
            crate::stats::LanguageCount,
            crate::stats::LibraryStats,
            crate::stats::TopSeries,
            crate::stats::MonthlyAdditions,
            crate::stats::MetadataStats,
            crate::stats::ProviderCount,
            crate::stats::CurrentlyReadingItem,
            crate::stats::RecentlyReadItem,
            crate::stats::MonthlyReading,
            crate::stats::UserMonthlyReading,
            crate::stats::JobTimePoint,
            crate::stats::DownloadStats,
            crate::stats::RecentDownloadItem,
            crate::libraries::LibraryResponse,
            crate::metadata::handlers::ExternalMetadataLinkDto,
            crate::metadata::handlers::MissingBooksDto,
            crate::metadata::handlers::MissingBookItem,
            ErrorResponse,
        )
    ),
    security(("Bearer" = [])),
    tags(
        (name = "books", description = "Book browsing, details, pages and thumbnails"),
        (name = "series", description = "Series browsing, filtering and details"),
        (name = "metadata", description = "Metadata links and missing volumes"),
        (name = "reading-progress", description = "Reading progress tracking per book"),
        (name = "search", description = "Full-text search across books and series"),
        (name = "authors", description = "Author browsing and listing"),
        (name = "stats", description = "Collection statistics and dashboard data"),
        (name = "libraries", description = "Library listing"),
        (name = "reading-lists", description = "Reading lists: curated ordered collections of series"),
    ),
    modifiers(&SecurityAddon)
)]
pub struct ClientApiDoc;

// ─── Admin API (admin scope — full access) ──────────────────────────────────

#[derive(OpenApi)]
#[openapi(
    paths(
        // Books
        crate::books::list_books,
        crate::books::get_book,
        crate::books::get_thumbnail,
        crate::books::pages::get_page,
        crate::books::convert_book,
        crate::books::update_book,
        crate::books::thumbnails::start_thumbnails_rebuild,
        crate::books::thumbnails::start_thumbnails_regenerate,
        // Series
        crate::series::list_series,
        crate::series::list_all_series,
        crate::series::get_series_by_id,
        crate::series::get_series_by_name,
        crate::series::get_series_metadata,
        crate::series::get_series_metadata_by_id,
        crate::series::update_series,
        crate::series::update_series_by_id,
        crate::series::delete_series,
        crate::series::delete_series_by_id,
        crate::series::ongoing_series,
        crate::series::ongoing_books,
        crate::series::series_statuses,
        crate::series::provider_statuses,
        crate::series::merge::merge_series,
        crate::series::create::create_series,
        crate::series::list_archived_series,
        crate::series::get_archived_series,
        // Reading
        crate::reading::progress::get_reading_progress,
        crate::reading::progress::update_reading_progress,
        crate::reading::progress::mark_series_read,
        crate::reading::status_match::start_match,
        crate::reading::status_match::get_match_report,
        crate::reading::status_match::get_match_results,
        crate::reading::status_push::start_push,
        crate::reading::status_push::get_push_report,
        crate::reading::status_push::get_push_results,
        // Search & Authors
        crate::search::search_books,
        crate::authors::list_authors,
        crate::stats::get_stats,
        crate::stats::get_reading_overview,
        // Libraries
        crate::libraries::list_libraries,
        crate::libraries::create_library,
        crate::libraries::delete_library,
        crate::libraries::scan_library,
        crate::libraries::update_monitoring,
        crate::libraries::update_metadata_provider,
        crate::libraries::update_reading_status_provider,
        // Indexing
        crate::index_jobs::enqueue_rebuild,
        crate::index_jobs::list_index_jobs,
        crate::index_jobs::get_active_jobs,
        crate::index_jobs::get_job_details,
        crate::index_jobs::stream_job_progress,
        crate::index_jobs::get_job_errors,
        crate::index_jobs::cancel_job,
        crate::index_jobs::list_folders,
        // Metadata
        crate::metadata::handlers::search_metadata,
        crate::metadata::handlers::create_metadata_match,
        crate::metadata::handlers::approve_metadata,
        crate::metadata::handlers::reject_metadata,
        crate::metadata::handlers::get_metadata_links,
        crate::metadata::handlers::get_missing_books,
        crate::metadata::handlers::delete_metadata_link,
        crate::metadata::batch::start_batch,
        crate::metadata::batch::get_batch_report,
        crate::metadata::batch::get_batch_results,
        crate::metadata::refresh::start_refresh,
        crate::metadata::refresh::start_refresh_all,
        crate::metadata::refresh::get_refresh_report,
        // Downloads
        crate::downloads::prowlarr::search_prowlarr,
        crate::downloads::prowlarr::test_prowlarr,
        crate::downloads::qbittorrent::add_torrent,
        crate::downloads::qbittorrent::test_qbittorrent,
        crate::downloads::detection::start_detection,
        crate::downloads::detection::get_detection_report,
        crate::downloads::detection::get_detection_results,
        crate::downloads::detection::get_latest_found,
        crate::downloads::detection::delete_available_download,
        // Settings & Tokens
        crate::settings::get_settings,
        crate::settings::get_setting,
        crate::settings::update_setting,
        crate::settings::clear_cache,
        crate::settings::get_cache_stats,
        crate::settings::get_thumbnail_stats,
        crate::settings::list_status_mappings,
        crate::settings::upsert_status_mapping,
        crate::settings::delete_status_mapping,
        crate::tokens::list_tokens,
        crate::tokens::create_token,
        crate::tokens::revoke_token,
        crate::tokens::delete_token,
        crate::tokens::update_token,
        // Users
        crate::users::accounts::list_users,
        crate::users::accounts::create_user,
        crate::users::accounts::update_user,
        crate::users::accounts::delete_user,
        crate::users::genre_restrictions::get_genre_restrictions,
        crate::users::genre_restrictions::add_genre_restriction,
        crate::users::genre_restrictions::remove_genre_restriction,
        crate::users::genre_restrictions::set_genre_restrictions,
        // Integrations
        crate::integrations::komga::sync_komga_read_books,
        crate::integrations::komga::list_sync_reports,
        crate::integrations::komga::get_sync_report,
        crate::integrations::anilist::get_status,
        crate::integrations::anilist::search_manga,
        crate::integrations::anilist::get_series_link,
        crate::integrations::anilist::link_series,
        crate::integrations::anilist::unlink_series,
        crate::integrations::anilist::get_series_link_by_id,
        crate::integrations::anilist::link_series_by_id,
        crate::integrations::anilist::unlink_series_by_id,
        crate::integrations::anilist::toggle_library,
        crate::integrations::anilist::list_unlinked,
        crate::integrations::anilist::list_links,
        crate::integrations::anilist_sync::preview_sync,
        crate::integrations::anilist_sync::sync_to_anilist,
        crate::integrations::anilist_sync::pull_from_anilist,
        // Genres
        crate::genres::list_genres,
        crate::genres::rename_genre,
        crate::genres::delete_genre,
        crate::genres::assign_genre,
        crate::genres::untagged_series,
        // Reading lists
        crate::reading_lists::list_reading_lists,
        crate::reading_lists::get_reading_list,
        crate::reading_lists::create_reading_list,
        crate::reading_lists::update_reading_list,
        crate::reading_lists::delete_reading_list,
        crate::reading_lists::add_series,
        crate::reading_lists::remove_series,
        crate::reading_lists::reorder_series,
    ),
    components(
        schemas(
            // Genres
            crate::genres::GenreDto,
            crate::genres::RenameGenreRequest,
            crate::genres::AssignGenreRequest,
            // Reading lists
            crate::reading_lists::ReadingListDto,
            crate::reading_lists::ReadingListDetailDto,
            crate::reading_lists::ReadingListSeriesDto,
            crate::reading_lists::CreateReadingListRequest,
            crate::reading_lists::UpdateReadingListRequest,
            crate::reading_lists::AddSeriesRequest,
            crate::reading_lists::ReorderSeriesRequest,
            // Books
            crate::books::ListBooksQuery,
            crate::books::BookItem,
            crate::books::BooksPage,
            crate::books::BookDetails,
            crate::books::UpdateBookRequest,
            crate::books::pages::PageQuery,
            crate::books::thumbnails::ThumbnailsRebuildRequest,
            // Series
            crate::series::SeriesItem,
            crate::series::SeriesPage,
            crate::series::ListAllSeriesQuery,
            crate::series::OngoingQuery,
            crate::series::SeriesMetadata,
            crate::series::SeriesLookup,
            crate::series::UpdateSeriesRequest,
            crate::series::UpdateSeriesResponse,
            crate::series::MergeSeriesRequest,
            crate::series::MergeSeriesResponse,
            crate::series::CreateSeriesRequest,
            crate::series::CreateSeriesResponse,
            crate::series::ArchivedSeriesItem,
            crate::series::ArchivedBookItem,
            crate::series::ArchivedSeriesDetail,
            crate::series::ArchivedSeriesReadingProgress,
            crate::series::ArchivedBookReadingProgress,
            // Reading
            crate::reading::progress::ReadingProgressResponse,
            crate::reading::progress::UpdateReadingProgressRequest,
            crate::reading::progress::MarkSeriesReadRequest,
            crate::reading::progress::MarkSeriesReadResponse,
            crate::reading::status_match::ReadingStatusMatchRequest,
            crate::reading::status_match::ReadingStatusMatchReportDto,
            crate::reading::status_match::ReadingStatusMatchResultDto,
            crate::reading::status_push::ReadingStatusPushRequest,
            crate::reading::status_push::ReadingStatusPushReportDto,
            crate::reading::status_push::ReadingStatusPushResultDto,
            // Search & Authors
            crate::search::SearchQuery,
            crate::search::SearchResponse,
            crate::search::SeriesHit,
            crate::authors::ListAuthorsQuery,
            crate::authors::AuthorItem,
            crate::authors::AuthorsPageResponse,
            crate::stats::StatsResponse,
            crate::stats::StatsOverview,
            crate::stats::ReadingStatusStats,
            crate::stats::FormatCount,
            crate::stats::LanguageCount,
            crate::stats::LibraryStats,
            crate::stats::TopSeries,
            crate::stats::MonthlyAdditions,
            crate::stats::MetadataStats,
            crate::stats::ProviderCount,
            crate::stats::CurrentlyReadingItem,
            crate::stats::RecentlyReadItem,
            crate::stats::MonthlyReading,
            crate::stats::UserMonthlyReading,
            crate::stats::JobTimePoint,
            crate::stats::DownloadStats,
            crate::stats::RecentDownloadItem,
            crate::stats::UserReadingOverview,
            crate::stats::UserReadingOverviewItem,
            crate::stats::UserReadingOverviewSeries,
            crate::stats::UserReadingOverviewSeriesBook,
            // Libraries
            crate::libraries::LibraryResponse,
            crate::libraries::CreateLibraryRequest,
            crate::libraries::UpdateMonitoringRequest,
            crate::libraries::UpdateMetadataProviderRequest,
            crate::libraries::UpdateReadingStatusProviderRequest,
            // Indexing
            crate::index_jobs::RebuildRequest,
            crate::index_jobs::IndexJobResponse,
            crate::index_jobs::IndexJobDetailResponse,
            crate::index_jobs::JobErrorResponse,
            crate::index_jobs::ProgressEvent,
            crate::index_jobs::FolderItem,
            // Metadata
            crate::metadata::ApproveRequest,
            crate::metadata::ApproveResponse,
            crate::metadata::SyncReport,
            crate::metadata::SeriesSyncReport,
            crate::metadata::BookSyncReport,
            crate::metadata::FieldChange,
            crate::metadata::MetadataSearchRequest,
            crate::metadata::SeriesCandidateDto,
            crate::metadata::MetadataMatchRequest,
            crate::metadata::ExternalMetadataLinkDto,
            crate::metadata::MissingBooksDto,
            crate::metadata::MissingBookItem,
            crate::metadata::MetadataBatchRequest,
            crate::metadata::MetadataBatchReportDto,
            crate::metadata::MetadataBatchResultDto,
            crate::metadata::MetadataRefreshRequest,
            crate::metadata::MetadataRefreshReportDto,
            // Downloads
            crate::downloads::prowlarr::ProwlarrSearchRequest,
            crate::downloads::prowlarr::ProwlarrRelease,
            crate::downloads::prowlarr::ProwlarrCategory,
            crate::downloads::prowlarr::ProwlarrSearchResponse,
            crate::downloads::prowlarr::MissingVolumeInput,
            crate::downloads::prowlarr::ProwlarrTestResponse,
            crate::downloads::qbittorrent::QBittorrentAddRequest,
            crate::downloads::qbittorrent::QBittorrentAddResponse,
            crate::downloads::qbittorrent::QBittorrentTestResponse,
            crate::downloads::detection::StartDownloadDetectionRequest,
            crate::downloads::detection::DownloadDetectionReportDto,
            crate::downloads::detection::DownloadDetectionResultDto,
            crate::downloads::detection::LatestFoundPerLibraryDto,
            crate::downloads::detection::AvailableDownloadDto,
            crate::downloads::detection::AvailableReleaseDto,
            // Settings & Tokens
            crate::settings::UpdateSettingRequest,
            crate::settings::ClearCacheResponse,
            crate::settings::CacheStats,
            crate::settings::ThumbnailStats,
            crate::settings::StatusMappingDto,
            crate::settings::UpsertStatusMappingRequest,
            crate::tokens::CreateTokenRequest,
            crate::tokens::TokenResponse,
            crate::tokens::CreatedTokenResponse,
            crate::tokens::UpdateTokenRequest,
            // Users
            crate::users::accounts::UserResponse,
            crate::users::accounts::CreateUserRequest,
            crate::users::genre_restrictions::UserGenreRestrictionsResponse,
            crate::users::genre_restrictions::AddGenreRestrictionRequest,
            crate::users::genre_restrictions::SetGenreRestrictionsRequest,
            // Integrations
            crate::integrations::komga::KomgaSyncRequest,
            crate::integrations::komga::KomgaSyncResponse,
            crate::integrations::komga::KomgaSyncReportSummary,
            crate::integrations::anilist::AnilistStatusResponse,
            crate::integrations::anilist::AnilistMediaResult,
            crate::integrations::anilist::AnilistSeriesLinkResponse,
            crate::integrations::anilist::AnilistSearchRequest,
            crate::integrations::anilist::AnilistLinkRequest,
            crate::integrations::anilist::AnilistLibraryToggleRequest,
            crate::integrations::anilist_sync::AnilistSyncPreviewItem,
            crate::integrations::anilist_sync::AnilistSyncItem,
            crate::integrations::anilist_sync::AnilistSyncReport,
            crate::integrations::anilist_sync::AnilistPullItem,
            crate::integrations::anilist_sync::AnilistPullReport,
            ErrorResponse,
        )
    ),
    security(("Bearer" = [])),
    tags(
        (name = "books", description = "Book browsing, details, pages and thumbnails"),
        (name = "series", description = "Series browsing, filtering and management"),
        (name = "reading-progress", description = "Reading progress tracking per book"),
        (name = "search", description = "Full-text search across books and series"),
        (name = "authors", description = "Author browsing and listing"),
        (name = "stats", description = "Collection statistics and dashboard data"),
        (name = "libraries", description = "Library management (create/delete/settings)"),
        (name = "indexing", description = "Index management and job control"),
        (name = "metadata", description = "External metadata providers and matching"),
        (name = "prowlarr", description = "Prowlarr indexer integration"),
        (name = "qbittorrent", description = "qBittorrent download client integration"),
        (name = "download-detection", description = "Download detection and available releases"),
        (name = "settings", description = "Application settings and cache management"),
        (name = "tokens", description = "API token management"),
        (name = "users", description = "Reader user management"),
        (name = "reading_status", description = "Reading status match and push jobs"),
        (name = "anilist", description = "AniList integration for reading status sync"),
        (name = "komga", description = "Komga read-status sync"),
        (name = "genres", description = "Genre management"),
        (name = "reading-lists", description = "Reading lists: curated ordered collections of series"),
        (name = "series (deprecated)", description = "Deprecated series endpoints (use direct /series/{id} variants)"),
    ),
    modifiers(&SecurityAddon)
)]
pub struct AdminApiDoc;

// ─── Shared ─────────────────────────────────────────────────────────────────

pub struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "Bearer",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .description(Some(
                            "Enter your API Bearer token (format: stl_<prefix>_<secret>)",
                        ))
                        .build(),
                ),
            );
        }
    }
}

#[derive(utoipa::ToSchema)]
pub struct ErrorResponse {
    #[allow(dead_code)]
    pub error: String,
}

#[cfg(test)]
#[path = "tests/openapi.rs"]
mod tests;
