use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::books::list_books,
        crate::books::get_book,
        crate::reading::progress::get_reading_progress,
        crate::reading::progress::update_reading_progress,
        crate::reading::progress::mark_series_read,
        crate::books::get_thumbnail,
        crate::series::list_series,
        crate::series::list_all_series,
        crate::series::ongoing_series,
        crate::series::ongoing_books,
        crate::books::convert_book,
        crate::books::update_book,
        crate::series::get_series_metadata,
        crate::series::get_series_by_name,
        crate::series::update_series,
        crate::series::delete_series,
        crate::series::get_series_by_id,
        crate::series::get_series_metadata_by_id,
        crate::series::update_series_by_id,
        crate::series::delete_series_by_id,
        crate::books::pages::get_page,
        crate::search::search_books,
        crate::index_jobs::enqueue_rebuild,
        crate::books::thumbnails::start_thumbnails_rebuild,
        crate::books::thumbnails::start_thumbnails_regenerate,
        crate::index_jobs::list_index_jobs,
        crate::index_jobs::get_active_jobs,
        crate::index_jobs::get_job_details,
        crate::index_jobs::stream_job_progress,
        crate::index_jobs::get_job_errors,
        crate::index_jobs::cancel_job,
        crate::index_jobs::list_folders,
        crate::libraries::list_libraries,
        crate::libraries::create_library,
        crate::libraries::delete_library,
        crate::libraries::scan_library,
        crate::libraries::update_monitoring,
        crate::libraries::update_metadata_provider,
        crate::tokens::list_tokens,
        crate::tokens::create_token,
        crate::tokens::revoke_token,
        crate::tokens::delete_token,
        crate::authors::list_authors,
        crate::stats::get_stats,
        crate::settings::get_settings,
        crate::settings::get_setting,
        crate::settings::update_setting,
        crate::settings::clear_cache,
        crate::settings::get_cache_stats,
        crate::settings::get_thumbnail_stats,
        crate::metadata::handlers::search_metadata,
        crate::metadata::handlers::create_metadata_match,
        crate::metadata::handlers::approve_metadata,
        crate::metadata::handlers::reject_metadata,
        crate::metadata::handlers::get_metadata_links,
        crate::metadata::handlers::get_missing_books,
        crate::metadata::handlers::delete_metadata_link,
        crate::series::series_statuses,
        crate::series::provider_statuses,
        crate::settings::list_status_mappings,
        crate::settings::upsert_status_mapping,
        crate::settings::delete_status_mapping,
        crate::downloads::prowlarr::search_prowlarr,
        crate::downloads::prowlarr::test_prowlarr,
        crate::downloads::qbittorrent::add_torrent,
        crate::downloads::qbittorrent::test_qbittorrent,
        crate::metadata::batch::start_batch,
        crate::metadata::batch::get_batch_report,
        crate::metadata::batch::get_batch_results,
        crate::metadata::refresh::start_refresh,
        crate::metadata::refresh::get_refresh_report,
        crate::integrations::komga::sync_komga_read_books,
        crate::integrations::komga::list_sync_reports,
        crate::integrations::komga::get_sync_report,
        crate::users::accounts::list_users,
        crate::users::accounts::create_user,
        crate::users::accounts::update_user,
        crate::users::accounts::delete_user,
        crate::tokens::update_token,
        crate::libraries::update_reading_status_provider,
        crate::reading::status_match::start_match,
        crate::reading::status_match::get_match_report,
        crate::reading::status_match::get_match_results,
        crate::reading::status_push::start_push,
        crate::reading::status_push::get_push_report,
        crate::reading::status_push::get_push_results,
        crate::integrations::anilist::get_status,
        crate::integrations::anilist::search_manga,
        crate::integrations::anilist::get_series_link,
        crate::integrations::anilist::link_series,
        crate::integrations::anilist::unlink_series,
        crate::integrations::anilist::get_series_link_by_id,
        crate::integrations::anilist::link_series_by_id,
        crate::integrations::anilist::unlink_series_by_id,
        crate::integrations::anilist::toggle_library,
        crate::integrations::anilist::list_unlinked,
        crate::integrations::anilist_sync::preview_sync,
        crate::integrations::anilist_sync::sync_to_anilist,
        crate::integrations::anilist_sync::pull_from_anilist,
        crate::integrations::anilist::list_links,
    ),
    components(
        schemas(
            crate::books::ListBooksQuery,
            crate::books::BookItem,
            crate::books::BooksPage,
            crate::books::BookDetails,
            crate::reading::progress::ReadingProgressResponse,
            crate::reading::progress::UpdateReadingProgressRequest,
            crate::reading::progress::MarkSeriesReadRequest,
            crate::reading::progress::MarkSeriesReadResponse,
            crate::series::SeriesItem,
            crate::series::SeriesPage,
            crate::series::ListAllSeriesQuery,
            crate::series::OngoingQuery,
            crate::books::UpdateBookRequest,
            crate::series::SeriesMetadata,
            crate::series::SeriesLookup,
            crate::series::UpdateSeriesRequest,
            crate::series::UpdateSeriesResponse,
            crate::books::pages::PageQuery,
            crate::search::SearchQuery,
            crate::search::SearchResponse,
            crate::search::SeriesHit,
            crate::index_jobs::RebuildRequest,
            crate::books::thumbnails::ThumbnailsRebuildRequest,
            crate::index_jobs::IndexJobResponse,
            crate::index_jobs::IndexJobDetailResponse,
            crate::index_jobs::JobErrorResponse,
            crate::index_jobs::ProgressEvent,
            crate::index_jobs::FolderItem,
            crate::libraries::LibraryResponse,
            crate::libraries::CreateLibraryRequest,
            crate::libraries::UpdateMonitoringRequest,
            crate::libraries::UpdateMetadataProviderRequest,
            crate::tokens::CreateTokenRequest,
            crate::tokens::TokenResponse,
            crate::tokens::CreatedTokenResponse,
            crate::settings::UpdateSettingRequest,
            crate::settings::ClearCacheResponse,
            crate::settings::CacheStats,
            crate::settings::ThumbnailStats,
            crate::settings::StatusMappingDto,
            crate::settings::UpsertStatusMappingRequest,
            crate::authors::ListAuthorsQuery,
            crate::authors::AuthorItem,
            crate::authors::AuthorsPageResponse,
            crate::stats::StatsResponse,
            crate::stats::StatsOverview,
            crate::stats::ReadingStatusStats,
            crate::stats::FormatCount,
            crate::stats::LanguageCount,
            crate::stats::LibraryStats,
            crate::stats::TopSeries,
            crate::stats::MonthlyAdditions,
            crate::stats::MetadataStats,
            crate::stats::ProviderCount,
            crate::stats::CurrentlyReadingItem,
            crate::stats::RecentlyReadItem,
            crate::stats::MonthlyReading,
            crate::stats::UserMonthlyReading,
            crate::stats::JobTimePoint,
            crate::stats::DownloadStats,
            crate::stats::RecentDownloadItem,
            crate::metadata::ApproveRequest,
            crate::metadata::ApproveResponse,
            crate::metadata::SyncReport,
            crate::metadata::SeriesSyncReport,
            crate::metadata::BookSyncReport,
            crate::metadata::FieldChange,
            crate::metadata::MetadataSearchRequest,
            crate::metadata::SeriesCandidateDto,
            crate::metadata::MetadataMatchRequest,
            crate::metadata::ExternalMetadataLinkDto,
            crate::metadata::MissingBooksDto,
            crate::metadata::MissingBookItem,
            crate::downloads::qbittorrent::QBittorrentAddRequest,
            crate::downloads::qbittorrent::QBittorrentAddResponse,
            crate::downloads::qbittorrent::QBittorrentTestResponse,
            crate::downloads::prowlarr::ProwlarrSearchRequest,
            crate::downloads::prowlarr::ProwlarrRelease,
            crate::downloads::prowlarr::ProwlarrCategory,
            crate::downloads::prowlarr::ProwlarrSearchResponse,
            crate::downloads::prowlarr::MissingVolumeInput,
            crate::downloads::prowlarr::ProwlarrTestResponse,
            crate::metadata::MetadataBatchRequest,
            crate::metadata::MetadataBatchReportDto,
            crate::metadata::MetadataBatchResultDto,
            crate::metadata::MetadataRefreshRequest,
            crate::metadata::MetadataRefreshReportDto,
            crate::integrations::komga::KomgaSyncRequest,
            crate::integrations::komga::KomgaSyncResponse,
            crate::integrations::komga::KomgaSyncReportSummary,
            crate::users::accounts::UserResponse,
            crate::users::accounts::CreateUserRequest,
            crate::tokens::UpdateTokenRequest,
            crate::libraries::UpdateReadingStatusProviderRequest,
            crate::reading::status_match::ReadingStatusMatchRequest,
            crate::reading::status_match::ReadingStatusMatchReportDto,
            crate::reading::status_match::ReadingStatusMatchResultDto,
            crate::reading::status_push::ReadingStatusPushRequest,
            crate::reading::status_push::ReadingStatusPushReportDto,
            crate::reading::status_push::ReadingStatusPushResultDto,
            crate::integrations::anilist::AnilistStatusResponse,
            crate::integrations::anilist::AnilistMediaResult,
            crate::integrations::anilist::AnilistSeriesLinkResponse,
            crate::integrations::anilist_sync::AnilistSyncPreviewItem,
            crate::integrations::anilist_sync::AnilistSyncItem,
            crate::integrations::anilist_sync::AnilistSyncReport,
            crate::integrations::anilist_sync::AnilistPullItem,
            crate::integrations::anilist_sync::AnilistPullReport,
            crate::integrations::anilist::AnilistSearchRequest,
            crate::integrations::anilist::AnilistLinkRequest,
            crate::integrations::anilist::AnilistLibraryToggleRequest,
            ErrorResponse,
        )
    ),
    security(
        ("Bearer" = [])
    ),
    tags(
        (name = "books", description = "Book browsing, details and management"),
        (name = "series", description = "Series browsing, filtering and management"),
        (name = "search", description = "Full-text search across books and series"),
        (name = "reading-progress", description = "Reading progress tracking per book"),
        (name = "authors", description = "Author browsing and listing"),
        (name = "stats", description = "Collection statistics and dashboard data"),
        (name = "libraries", description = "Library listing, scanning, and management (create/delete/settings: Admin only)"),
        (name = "indexing", description = "Search index management and job control (Admin only)"),
        (name = "metadata", description = "External metadata providers and matching (Admin only)"),
        (name = "komga", description = "Komga read-status sync (Admin only)"),
        (name = "tokens", description = "API token management (Admin only)"),
        (name = "settings", description = "Application settings and cache management (Admin only)"),
        (name = "prowlarr", description = "Prowlarr indexer integration (Admin only)"),
        (name = "qbittorrent", description = "qBittorrent download client integration (Admin only)"),
        (name = "users", description = "Reader user management (Admin only)"),
        (name = "reading_status", description = "Reading status match and push jobs (Admin only)"),
        (name = "anilist", description = "AniList integration for reading status sync (Admin only)"),
    ),
    modifiers(&SecurityAddon)
)]
pub struct ApiDoc;

pub struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "Bearer",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .description(Some(
                            "Enter your API Bearer token (format: stl_<prefix>_<secret>)",
                        ))
                        .build(),
                ),
            );
        }
    }
}

#[derive(utoipa::ToSchema)]
pub struct ErrorResponse {
    #[allow(dead_code)]
    pub error: String,
}

#[cfg(test)]
#[path = "tests/openapi.rs"]
mod tests;
