[package]
name = "notifications"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
stripstream-core = { path = "../core" }
tokio.workspace = true
tracing.workspace = true
